### ISSUE TITLE
Update on search fields

### ISSUE THREAD

**Issue by angelawachowich** [sfu-dhil/mvm#102]
Can we get an updated list of what field(s) each search line covers?

**Comment by ubermichael** [comment]
The GitHub issue queue isn't a good place to ask general questions like this. Issues are for bugs in the site or to request specific features. 

- Archives: label, description
- Poems: title, first line, transcription, author name, author variant names
- Coteries: label, description
- Manuscripts
  - call number and description without quotes
  - call number with quotes
- People: name, variant names
- Print sources: label, description
- Region: name
- Theme: label, description

**Comment by schellenb** [comment]
Thanks, Michael, this list is what we were after. Betty.
