### ISSUE TITLE
How to make changes to the descriptors under each item in the explore menu

### ISSUE THREAD

**Issue by angelawachowich** [sfu-dhil/mvm#103]
How do we make changes to the one-line descriptors under each item in the explore menu? eg below "A group of individuals who interacted with one another and shared similar interests"
<img width="736" alt="Screenshot 2021-02-03 at 2 50 08 PM" src="https://user-images.githubusercontent.com/67483719/106819910-532ebc80-662f-11eb-91fe-78c178c1146d.png">

**Comment by joeytakeda** [comment]
Those are hard-coded into the pages, so they're not editable through the database. You can let us know, though, which pages need to be changed and what should go there.

**Comment by schellenb** [comment]
Hi. Finally went through the descriptors and there are 3 that need to be changed:

1. Poem roles: [lacks description altogether] insert: Roles played by individuals in relation to specific poems

2. Coteries: A group of individuals who interacted with one another and shared similar interests → change to: A social network of individuals whose activities feature the exchange of original poetry and other literary pursuits

3. Features: Bibliographical, decorative, organizational, or user features of a manuscript → change “user” to: user-related

Thanks.
Betty
