### ISSUE TITLE
Tab image

### ISSUE THREAD

**Issue by angelawachowich** [sfu-dhil/mvm#104]
Can we change this picture? 
<img width="337" alt="Screenshot 2021-02-03 at 2 36 11 PM" src="https://user-images.githubusercontent.com/67483719/106820207-ca645080-662f-11eb-9d03-06efe5854718.png">

**Comment by joeytakeda** [comment]
Yep! I just added it in quickly to add a simple favicon. Anything you'd prefer it to be?

**Comment by angelawachowich** [comment]
<img width="110" alt="Screenshot 2021-02-03 at 3 09 44 PM" src="https://user-images.githubusercontent.com/67483719/106821395-e832b500-6631-11eb-8182-da73fe2a4f5e.png">
?

**Comment by joeytakeda** [comment]
I thought that as well—see #38 . The main issue is that MVM itself won’t fit in the tiny square allocated to the favicon. If we wanted to go down that route, it would probably have to be just the “m” of “mvm”.  But agreed that the marbled background isn’t great!

What about a fleuron? That’s not distinct to the project, but it would fit nicely and it’s used throughout the site. It could be a white fleuron on a purple background or a purple fleuron with a transparent background.

**Comment by schellenb** [comment]
Hi Joey and Angela,

I would prefer either a white M (in one of the 2 scripts used) on purple background or a white fleuron on a purple background.

Thanks. Betty.
