### ISSUE TITLE
"Text" field in People table

### ISSUE THREAD

**Issue by schellenb** [sfu-dhil/mvm#120]
This is probably not a bug, technically, but it might be a vestigial feature. I am trying to recall what the field called “Text,” just under “Links,” does in the Person entry table. I recall this question coming up in a meeting, but I don’t seem to have a note about it. Was it going to be removed? Or was it there in case of a print reference that we might want to enter as a source of biographical information? At this point, this field is not being used. Thank-you.

**To Reproduce**
4. The error is '....'

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by ubermichael** [comment]
The Text field in Links sets the text of the link. It's the clickable word or phrase. If you leave it blank, the text field will be generated from the domain name in the URL field.

**Comment by schellenb** [comment]
Thanks for the clarification, Michael. I think you explained this once before, but I hadn’t made a note on it, so wasn’t sure.

Best,
Betty
