### ISSUE TITLE
Error sorting pages

### ISSUE THREAD

**Issue by ubermichael** [sfu-dhil/mvm#138]
## What isn’t working as expected on the website? 
Sorting blog pages isn't working.

## If you encountered an error message, please copy the relevant details or take a screenshot and paste it below. (Type NA if not applicable.)
2021-10-05T11:07:19-07:00
174.7.183.0
GET https://dhil.lib.sfu.ca/mvm/blog/page/sort
https://dhil.lib.sfu.ca/mvm/blog/page/sort
500 - Error
Call to a member function setWeight() on null
Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:92.0) Gecko/20100101 Firefox/92.0

There are also some javascript errors.

## What is the URL of the page where you encountered the bug? [Type NA if not applicable.]

https://dhil.lib.sfu.ca/mvm/blog/page/sort

## What steps did you take before you encountered the bug?

Sort the pages and save.

## What browser, operating system, and device were you using when you encountered the error?

Firefox

**Comment by joeytakeda** [comment]
I've fixed this already :-)
