### ISSUE TITLE
Manuscript "Search" Bug

### ISSUE THREAD

**Issue by angelawachowich** [sfu-dhil/mvm#139]
When I search "Jacobite" in the Manuscript search I receive no results. https://dhil.lib.sfu.ca/mvm/manuscript/search?q=%22jacobite%22. The word "Jacobite" appears in at least two manuscript descriptions (Leeds Brotherton Lt 106 and Folger MS M.a.169), and we expected the search to turn up these two results. This is a bug because the search function is meant to search Manuscript description (as well as call number and title).

I encountered this error while on Safari.

**Comment by ubermichael** [comment]
Hello Angela. Searching for jacobite with quotes is the problem. We use quotation marks to search for call numbers only. Searching for jacobite without quotes will show the two expected search results.
