### ISSUE TITLE
Rich text editor should paste with formatting

### ISSUE THREAD

**Issue by joeytakeda** [sfu-dhil/mvm#146]
(Reported by BSch)

## What isn’t working as expected on the website? 

Pasting in lists from Word creates extra spaces that need to be cleaned up manually

## If you encountered an error message, please copy the relevant details or take a screenshot and paste it below. (Type NA if not applicable.)

NA

## What is the URL of the page where you encountered the bug? [Type NA if not applicable.]

All editing pages

## What steps did you take before you encountered the bug?

Go to Microsoft Word, make a list, and then paste it into a new blog page. The list is converted to text and the formatting is not preserved

## What browser, operating system, and device were you using when you encountered the error?

All

## Additional context

The configuration should be switched for TinyMCE to allow for pasting with formatting

**Comment by schellenb** [comment]
This sounds like a helpful solution, thanks. Just to clarify: we can't even figure out how to clean this up manually when there is a spacing problem - the double-spacing just kicks in whenever "enter" is used and we can't find a way to work around it. But hopefully this will no longer be an issue when the formatting configuration is changed.
