### ISSUE TITLE
Manuscript search for title term "Scraps"

### ISSUE THREAD

**Issue by schellenb** [sfu-dhil/mvm#160]
### What isn’t working as expected on the website?

When I enter the term "Scraps" into the search field for manuscripts, I expect a result for Beinecke Osborn c481 with the title "Select and Miscellaneous Poems, Scraps, Mottos &c." but I get no results. I have tried with lower- and upper-case "s" and with a comma at the end. No luck

### If you encountered an error message, please copy the relevant details or take a screenshot and paste it below.

N/A

### What is the URL of the page where you encountered the bug?

https://dhil.lib.sfu.ca/mvm/manuscript/search?q=scraps

### What steps did you take before you encountered the bug?

> Browse all MSS > searchline 

### What browser, operating system, and device were you using when you encountered the error?

Firefox on my PC

**Comment by ubermichael** [comment]
Please try a search for "scraps" with the quotation marks included. The quotation marks indicate the search term is a call number or a title.

This is how I understood https://github.com/sfu-dhil/mvm/issues/116 for using quotes for title searches.
