### ISSUE TITLE
Order of themes in Manuscript Details

### ISSUE THREAD

**Issue by angelawachowich** [sfu-dhil/mvm#165]
### Describe the feature

Currently, Themes connected to a manuscript (which appear under Manuscript Details) appear in alphabetical order. Instead, we would like them to appear in the order we connect them to the database.

### How will this feature enhance your project and further the project’s overall goals? Who will benefit from this feature (i.e. all users; the project team)?

We would like the themes to appear in the order we enter them so that we can list them in descending order of prominence. This will make it clearer for users which themes are most important to the manuscript and which themes feature less prominently.

### Are there any alternatives for this feature? Are there any consequences for your project if this feature is not implemented?

No alternative come to mind but I will give this some more thought if necessary.

### Please share any examples of this feature, or one similar to it, that you have encountered in other contexts.

n/a

**Comment by angelawachowich** [comment]
Themes do not appear in the order I enter them. For example, if I enter these themes in this order into the Themes box of Beinecke Osborn fc132 (Death, afterlife; Women; Conduct, morality; Travel; Courtship, marriage; Passions; Domestic life; Nature; Solitude, loneliness, retirement; Public affairs; Classical themes; Historical subjects; Animals, pets), they reorganise as I'm typing them so that they look like this:
<img width="640" alt="Screenshot 2022-03-01 at 12 17 08 PM" src="https://user-images.githubusercontent.com/67483719/156244927-9540a69b-c45d-4676-960b-404bab3e4ec8.png">

And appear like this when I save changes:
<img width="839" alt="Screenshot 2022-03-01 at 12 14 59 PM" src="https://user-images.githubusercontent.com/67483719/156244947-850609de-31ea-49ac-8077-b0cb0bc7028b.png">

**Comment by angelawachowich** [comment]
Hi @ubermichael, perhaps I'm reading this record wrong, but just a heads up that this issue was not fixed by #167.

**Comment by ubermichael** [comment]
I think I misunderstood. Do you want the order of the themes to be the same in every manuscript, or do you want to specify the order on a manuscript by manuscript basis?

**Comment by angelawachowich** [comment]
I want to specify the order on a manuscript to manuscript basis, please.

**Comment by angelawachowich** [comment]
Hi @ubermichael, just a friendly reminder that I need the order of the themes on the database to be updated so that I can specify the order on a manuscript to manuscript basis.

**Comment by ubermichael** [comment]
Hi @angelawachowich I'm still trying to find a simple way to implement this. I'm not sure there is one.

**Comment by ubermichael** [comment]
Hi Betty, I'm working on this today. It's a much better solution, I think.
