### ISSUE TITLE
Search function for poems

### ISSUE THREAD

**Issue by schellenb** [sfu-dhil/mvm#169]
### What isn’t working as expected on the website?

Some poems don't turn up via searches of keywords from first line or via phrases from first line in qtn marks.
- eg: I heard the Sisters of the sacred well
- eg: Hear all you friends to Knighthood

### If you encountered an error message, please copy the relevant details or take a screenshot and paste it below.

NA

### What is the URL of the page where you encountered the bug?

https://dhil.lib.sfu.ca/mvm/content/

### What steps did you take before you encountered the bug?

1. Went to Poems option
2. Selected Browse all poems
3. completed search line with several alternatives - eg. sisters, Sisters, "I heard the Sisters", "I heard the Sisters of the sacred well"

### What browser, operating system, and device were you using when you encountered the error?

Firefox on my PC

### Additional information

Some poem searches are working, so I haven't figured out how to tell which ones are not.

**Comment by schellenb** [comment]
I've encountered the same problem with a third poem - a search for "Indulgent Nature" (with or without qtn marks) does NOT turn up the poem "Indulgent Nature to each kind bestows," but it DOES turn up the poem "Indulgent God, whose bounteous care." So it doesn't seem to be an issue of the search string being too short.

**Comment by ubermichael** [comment]
These poems were not included in the search results because the code only considered poems with an author. I've corrected the code to account for it and will update the site soon.

**Comment by schellenb** [comment]
Thanks, Michael. The poem searches seem to be working well now.

Best,
Betty
