### ISSUE TITLE
Table of Contents data

### ISSUE THREAD

**Issue by ubermichael** [sfu-dhil/mvm#50]
Should this take the form of free-text entries in the Manuscript table or of separate documents? If the former, could individual Content items be linked to their appearance elsewhere in the database? (Depending on the solution, as researchers we need to decide how the data should be standardized for title, first line, author, etc.– currently the Tables of Contents are in the form of exact transcriptions.

**Comment by ubermichael** [comment]
There is already a contents tab for manuscripts (https://dhil.lib.sfu.ca/mvm/manuscript/13) but it only lists content entries in the database. I can create a free-text field for a table of contents, but I'm not sure that's exactly what they need.

**Comment by michael-joyce** [comment]
The decision is to close this issue and revisit in the future when time permits.
