### ISSUE TITLE
Advanced search

### ISSUE THREAD

**Issue by ubermichael** [sfu-dhil/mvm#52]
This may not be necessary or feasible in this work period, but it is possible
that as we work with the user interface, we will decide that particular sorts of multi-faceted searches are especially desirable (e.g. which miscellanies containing Jacobite themes are linked with the Yorkshire region?) If so, this could be discussed and planned for.

**Comment by rcastong** [comment]
example comment

**Comment by ubermichael** [comment]
Closing, because this has been largely superseded by other issues.
