### ISSUE TITLE
Add support for a home page

### ISSUE THREAD

**Issue by michael-joyce** [sfu-dhil/mvm#64]
I forgot to do this when setting up the site.

**Comment by joeytakeda** [comment]
As far as I know, this should already be done from the redesign; there's handling for it in the twig file and the controller:


https://github.com/sfu-dhil/mvm/blob/6e4e93bebe57249aa9c06730b3a4bb03c53d9ae8/templates/default/index.html.twig#L10-L16

https://github.com/sfu-dhil/mvm/blob/6e4e93bebe57249aa9c06730b3a4bb03c53d9ae8/src/Controller/DefaultController.php#L47

**Comment by ubermichael** [comment]
Looks like I was looking at an old version of the code. Silly me.
