### ISSUE TITLE
Determine display for people biographies vs description

### ISSUE THREAD

**Issue by joeytakeda** [sfu-dhil/mvm#67]
People now have a "biography" field, which is distinct from their description, but it's not totally clear from the display what the difference is between the "biography" and the "description." The biographies won't be very long and will often link out to other resources.

So first thing we need is a clear definition of what each of those mean and what will go into one versus the other. At the moment, there aren't a ton of descriptions and most of them are fairly brief ("Part of the Peart-Bate coterie.") and I don't seem to see any biographies yet. 

A few questions to work through, first:

* What is the difference between descriptions and biographies?
* Should people have both?
* If someone can have both, what is their relationship?
* Should people have neither?

Depending on the above, there are a few ways forward:

* Descriptions are _internal_ and informal notes about that person; Biographies are what users of the site see.
* Descriptions are short abstracts about that person (i.e. like a gloss); Biographies are longer and more formal descriptions of the person. Both would be displayed, but potentially collapsed into one block on them page. 

Depending on how these two bits of data should interact, one idea for the display is placing biographies/descriptions below the heading, but before the fleuron on people pages. Since biographies could be multi-paragraph, we could clip it at a particular length (i.e. max 4 lines), and then have a "READ MORE" link that shows the full content. Something like this:

![Screen Shot 2020-12-22 at 10 10 40 AM](https://user-images.githubusercontent.com/17664763/102919626-05bf0d00-443e-11eb-85f0-9430fe2455a3.png)

Once we have a sense of this, we'll need to consider whether or not there'll be enough information to make links to people a bit more helpful/informative to users (Info popups, tooltips, etc). That would be helpful for people who are reading a poem, for instance, and want to get some information about the author/compiler/whoever, but don't want to switch contexts from the poem to the person.

**Comment by schellenb** [comment]
•	Description should be visible to users. It is very short abstract; primarily in relation to miscellanies and relations to others involved in the same miscellany or coterie; may where possible include brief phrase re: occupation, literary activities – we will do a thorough review of these shortly
•	for bios all we want is a link to ODNB (or Orlando or Wikipedia or any other fairly reliable and stable source?), which we are now entering in “links”
•	therefore, we do not need the Biographies section after all. (whoops?)
Re:  having the description under the heading and before the fleuron - this might be very nice. Should we wait till we redo the descriptions and see what length they end up being?
Re: idea of info pop-ups, tooltips, etc. - That sounds interesting, especially for the brief description, but we need more info about what this would entail/imply. Maybe at some point we could also talk about making the people page more user-friendly in how it displays.

**Comment by joeytakeda** [comment]
We talked about this briefly at the meeting today.  To summarize:

* Biographies are going to removed (#82) and the link field will be renamed (#83)
* Links to people should become popup modals rather than straight links (except when linking from the actual listing table). Those modals will contain a smaller subset of information that will basically act as a gloss for the person--that's kinder to users who are in the midst of reading a poem, for instance, and want to know who someone is, but doesn't want to stray away from what they're reading.

We still need to think about the full person page a bit and see what kinds of stuff we might want to do with it.
