### ISSUE TITLE
Search fields feedback

### ISSUE THREAD

**Issue by schellenb** [sfu-dhil/mvm#71]
I have reviewed the Search fields list that Michael sent via Remi on Nov. 30th; please see my comments below:

1.	(done) Archives, Coteries, Periods, Print Sources, Regions, and Themes

-	Michael: Searches the label [e.g. archive name, title of source, etc.] and description fields for that item. For example, searching for “behaviour” or “celebrities” in the themes page will produce a results page with one result.

-	Betty: 
o	**Periods is not actually searchable, and I don’t think it needs to be
o	Why does Coteries present a search button to click on, rather than the search option right on the page? It would be preferable to have the search mechanism here match the others. [Also, could the Coteries table include a “Region” field? Many of the coteries are based in a particular community or region. I will add this to GitHub as a separate issue.] The region field should then also be included in the search.
o	The Print Sources search could be very useful – it should include the Region field as well
-	Regions – there is no description field for this, so does the search only cover the place name? This would be ok.**

2.	(done) Contents [now “Poems”]

-	Michael: Searches the title, firstLine, and transcription fields – Betty: **please add author**

3.	(done) Manuscripts

-	Michael: Searches the manuscript call number and title fields – Betty: **please add description field**

4.	(done) People

-	Michael: Searches the full name field. – Betty: **please include variant name to cover aristocratic titles and maiden names**

5.	Features

-	Betty: **currently not searchable, but features is quite a long list – please add a search function that covers feature name and descriptions because it could be useful to search things like “blank book” or “pagination” or “illustrations,” where the searcher might not know what we have called that feature, or the general feature under which we have place it**

**Comment by joeytakeda** [comment]
To answer this bit:

> Why does Coteries present a search button to click on, rather than the search option right on the page? It would be preferable to have the search mechanism here match the others. 

The coteries are currently still in a "beta" stage as far as I understand it; the data structure is there, but they haven't been integrated into the look/feel of the site. I see that there are a number of coteries now, so we should definitely come up with a plan for how those should display. I'll open a new ticket for that.

**Comment by schellenb** [comment]
Ok, thanks for the clarification, Joey. I will be working on individual coterie descriptions this week.

Best,
Betty

Betty A. Schellenberg, PhD, FRHistS
Professor of English
Simon Fraser University
Burnaby BC Canada
V5A 1S6
schellen@sfu.ca
778-782-3136
www.cambridge.org/9781107128163<http://www.cambridge.org/9781107128163>

**Comment by ubermichael** [comment]
- Item 1 in the big list has been separated out to #74 and #72
- Item 2 has been moved out to #75
- Item 4 has been split out to #77
- Item 3 is recorded in #78
