### ISSUE TITLE
Coteries - additional region field

### ISSUE THREAD

**Issue by schellenb** [sfu-dhil/mvm#72]
As mentioned on the Search Fields issue post, here are 2 items related to Coteries:

- ~~In Coteries, there is no search line to be filled in, only a search button on the right. Could this be adjusted to match the other Explore items (archives, etc.)?~~ (Moved to #73)
- Could we add a Region field to the Coteries table? Coteries are often characterized by the community or region in which they are found.

Thank-you.

**Comment by joeytakeda** [comment]
I've added a separate ticket for the display of coteries (#73), so we can address the search bar stuff there; I'll retitle this ticket slightly so that this one can be just about the additional region field.

**Comment by schellenb** [comment]
Makes sense, thank-you. Betty.

Betty A. Schellenberg, PhD, FRHistS
Professor of English
Simon Fraser University
Burnaby BC Canada
V5A 1S6
schellen@sfu.ca
778-782-3136
www.cambridge.org/9781107128163<http://www.cambridge.org/9781107128163>

**Comment by michael-joyce** [comment]
I can add the field to the coteries, sure. But I'll also need to know a little more about what you'd like to do with the field.

1. Do you want to see all the coteries in a particular region on one page?
2. Do you want to see all the coterie regions on one page to browse them?
3. Will the list of regions be identical to the list at https://dhil.lib.sfu.ca/mvm/region/ ?
4. If it is the same as the list in 3, should the linked page be updated to include a count of the coteries in each region?

**Comment by ubermichael** [comment]
The "ghost" user above was me, posting comments from an account that I have since deleted.

**Comment by schellenb** [comment]
Michael, here are my responses to your questions:
1.	Do you want to see all the coteries in a particular region on one page? 
Betty: Would this page be created via search results? We think the search function would be adequate for the number of coteries we have if region is part of the coteries search fields; however, we need to standardize region naming, which is the next thing we will work on.
2.	Do you want to see all the coterie regions on one page to browse them? 
Betty: Searchability of regions via coteries would be adequate for our number of coteries
3.	Will the list of regions be identical to the list at https://dhil.lib.sfu.ca/mvm/region/ ?
Betty: Yes, we will address this, as indicated above.
4.	If it is the same as the list in 3, should the linked page be updated to include a count of the coteries in each region? 
Betty: Yes, please – presumably an added column to the regions display

**Comment by schellenb** [comment]
Also, we could delete the members display on the coteries page and replace this with region. The members number is just a reflection of who we know and can name, so it is quite arbitrary and likely inaccurate.

**Comment by ubermichael** [comment]
I've done the database stuff, so passing this off to @joeytakeda especially for the last few comments.
