### ISSUE TITLE
Links of people with coteries

### ISSUE THREAD

**Issue by schellenb** [sfu-dhil/mvm#81]
This is a separate response to Joey's questions.

1. Suggestion of a link of person to coterie that would list all of the other members of the coterie: this would be useful and convenient.
2. Will we need to deal with one person being in more than one coterie? We are not sure this needs special handling, because the cases of such interconnection, while fascinating, are extremely rare in our limited set of coteries.

**Comment by joeytakeda** [comment]
I think we should handle this much like we will handle people: a link to a coterie would open a modal popups that contain their description as well as the list of all their members. But anything to do with coteries should probably wait until the coteries and manuscripts have a proper link (per #86).

**Comment by ubermichael** [comment]
Unassigned myself, as the database side of things is complete. Over to you @joeytakeda

**Comment by joeytakeda** [comment]
This should now be done, so closing this issue.
