### ISSUE TITLE
Manuscripts open in new tab instead of same window

### ISSUE THREAD

**Issue by angelawachowich** [sfu-dhil/mvm#92]
Would it be possible to have the individual manuscripts open in a new tab when selected from the Manuscript list page? Right now, they open in the same tab, which makes it difficult to go back to the same page of the Manuscript list afterwards.

**Comment by ubermichael** [comment]
Handing this off to @joeytakeda since it's a UI change.

**Comment by joeytakeda** [comment]
Discussed today and determined that this wasn’t necessary, so I’m going to close this issue
