### ISSUE TITLE
"hiding" manuscripts

### ISSUE THREAD

**Issue by schellenb** [sfu-dhil/mvm#94]
A question I meant to ask Joey this afternoon: we are deleting some entries of databases which we have no likelihood of seeing or getting adequate information on. However, there are others that I am still hoping to see in the not-too-distant future, especially at the Beinecke Library. Is there any reason why I shouldn't keep these on the database but not designate them as "complete," so that they stay hidden as drafts even after the site goes public?

**Comment by joeytakeda** [comment]
Depends on what the goal is for these items. One solution, as you said, is to hide manuscripts from public users on the listing pages etc. That's @ubermichael's domain, though, so I'll let him address how complicated that might be to implement. 

Another solution is to show all of the manuscripts to everyone, but the ones that are marked as not complete could have some special display that alerts the user that the entry is incomplete (maybe a draft watermark background or a little notice somewhere saying "Note: This manuscript entry is incomplete" or some such). That way, even if an entry never does becomes "complete," there's still some record of its existence on the site.

**Comment by ubermichael** [comment]
The two options (hiding some manuscripts from view or displaying a message that they are incomplete) are the same amount of work. And that's not a lot of work to be done.

I'll work on this in the next few days, going with the hidden option unless I hear otherwise.

**Comment by joeytakeda** [comment]
Regardless of the option, though, there will need to be interface work to denote whether or not the the manuscript is in draft (both on the manuscript page and anywhere that it’s listed). That might be a big red banner or a watermark or a different border or something else entirely. 

That said, as far as I understand it, If the draft manuscripts aren’t hidden from public view, then this is just something that can be dealt with at an interface level.

**Comment by ubermichael** [comment]
At a minimum there will need to be a new field, so some change to the database is required.

**Comment by schellenb** [comment]
Hi Michael,

Thanks for the heads-up. Can I just confirm that:


  *   Once this is set up, we as editors would have control of the process for setting a ms to “hide” for now, and
  *   we would in the future then be able to “unhide” a ms as we wished (or, alternatively, delete it completely)


Assuming that is the case, I think the hidden option is best for now.

Best,
Betty

Betty A. Schellenberg, PhD, FRHistS
Professor of English
Simon Fraser University
Burnaby BC Canada
V5A 1S6
schellen@sfu.ca
778-782-3136
www.cambridge.org/9781107128163<http://www.cambridge.org/9781107128163>

**Comment by ubermichael** [comment]
The manuscript new and edit forms have two "Save As..." buttons. The "Save as Draft" button marks the manuscript as incomplete in the database. We can hide those incomplete manuscripts from the public view but let them be visible to people who have logged in. The "Save as Complete" button marks the manuscript as complete and we can make those complete manuscripts public.

Right now there are no complete manuscripts in the database.

**Comment by joeytakeda** [comment]
Just to keep this up to date: draft manuscripts now have a little badge stating that they are in draft.

**Comment by schellenb** [comment]
Yes, I did notice that. Informative but not intrusive. Thanks. B.

**Comment by ubermichael** [comment]
Draft vs. complete is sufficient and there's no need to hide the drafts.
