### ISSUE TITLE
Renaming "Major Contributor" to "Major Author"

### ISSUE THREAD

**Issue by schellenb** [sfu-dhil/mvm#95]
Could we please rename the Manuscript Role "Major Contributor" to "Major Author"? Way back we were using the term "contributor" in case this included other functions, like illustration, but the term is in fact only being used for authors of poems. "Major Author" matches our vocabulary better and would be clearer to the uninitiated user of the database. Thanks.

**Comment by joeytakeda** [comment]
Hi Betty--you should be able to do the renaming (and the description if you'd like) yourself through the edit screen:

https://dhil.lib.sfu.ca/mvm/manuscript_role/4

Let me know, though, if you run into any issues!

**Comment by schellenb** [comment]
Done, thanks.
